#!/bin/sh
# Copyright 2025 Altera Corporation

# Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
# and associated documentation files (the “Software”), to deal in the Software without 
# restriction, including without limitation the rights to use, copy, modify, merge, publish, 
# distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the 
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or 
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR 
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
# OTHER DEALINGS IN THE SOFTWARE.

# Check required tools
PARTED=$(which parted) || exit 1
PARTPROBE=$(which partprobe) || exit 1
RESIZE2FS=$(which resize2fs) || exit 1

# Find root partition device
ROOT_PART_DEVICE=$(findmnt / -o source -n)

# Get root device name
ROOT_PART_NAME=$(echo "$ROOT_PART_DEVICE" | cut -d "/" -f 3)
ROOT_DEVICE_NAME=$(echo /sys/block/*/"${ROOT_PART_NAME}" | cut -d "/" -f 4)
ROOT_DEVICE="/dev/${ROOT_DEVICE_NAME}"

# Get root partition number
PART_NUMBER=$(cat "/sys/block/${ROOT_DEVICE_NAME}/${ROOT_PART_NAME}/partition")

# Get device size
DEVICE_SIZE=$(cat "/sys/block/${ROOT_DEVICE_NAME}/size")
PART_SIZE=$((DEVICE_SIZE - 1))

#
# Resize partition
#
${PARTED} -m ${ROOT_DEVICE} u s resizepart ${PART_NUMBER} ${PART_SIZE}
${PARTPROBE}
${RESIZE2FS} "${ROOT_PART_DEVICE}"

