header:
  version: 17

repos:
  meta-oe:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: wrynose
    path: layers/meta-openembedded
    commit: 420222862f5a6d95023b8f5f3b7e1808b2264ef9
    layers:
      meta-oe:

local_conf_header:
  meta-altera-fpga-dev: |
    EXTRA_IMAGE_FEATURES:append = " allow-empty-password allow-root-login empty-root-password ssh-server-openssh"
    IMAGE_INSTALL:append = " \
        packagegroup-fpga-embedded-tools \
        git \
        htop \
    "
