header:
  version: 17
repos:
  meta-oe:
    url: "https://git.openembedded.org/meta-openembedded"
    commit: 4d3e2639dec542b58708244662d5ce36810fc510
    branch: scarthgap
    path: layers/meta-openembedded
    layers:
      meta-oe:
local_conf_header:
  meta-altera-fpga-dev: |
    EXTRA_IMAGE_FEATURES:append = " debug-tweaks ssh-server-openssh"
    IMAGE_INSTALL:append = " \
        packagegroup-fpga-embedded-tools \
        git \
        htop \
    "
