/*******************************************************************************
Copyright (C) Altera Corporation

This code and the related documents are Altera copyrighted materials and your
use of them is governed by the express license under which they were provided to
you ("License"). This code and the related documents are provided as is, with no
express or implied warranties other than those that are expressly stated in the
License.
*******************************************************************************/

/*
 ***** THIS FILE IS AUTO-GENERATED DO NOT MODIFY *****
 * Generated 2026-06-26 @ 07:38:53
 */

#include "IpCapabilityNames.h"

namespace Hapi
{
    const std::unordered_map<uint32_t, std::string>& GetCapabilityNames()
    {
        static std::unordered_map<uint32_t, std::string> capabilityNames = 
        {
        { 0x0000, "Placeholder" },
        { 0x0010, "Timer Capability V2" },
        { 0x0012, "OmniTek Altera Video Input V3" },
        { 0x0013, "OmniTek Altera Video Output V3" },
        { 0x0014, "OmniTek Altera Generic Interrupt" },
        { 0x0102, "Bi-Directional Data MDMA V5" },
        { 0x0104, "Data In FDMA V5" },
        { 0x0105, "Data Out FDMA" },
        { 0x0114, "Video In FDMA V5" },
        { 0x0115, "Video Out FDMA" },
        { 0x0134, "Packet In FDMA" },
        { 0x0135, "Packet Out FDMA" },
        { 0x0163, "Intel VVP Tone Mapping Operator" },
        { 0x0165, "Intel VVP 3D Lut" },
        { 0x016F, "Intel Scalable Warp Processor" },
        { 0x0170, "Intel VVP Clocked Video In" },
        { 0x0171, "Intel VVP Generic Crosspoint" },
        { 0x0172, "Intel VVP Genlock Router" },
        { 0x0173, "Intel VVP CVI_2_VVPLite" },
        { 0x0174, "Intel VVP Black Level Stats" },
        { 0x0175, "Intel VVP Defective Pixel Correction" },
        { 0x0176, "Intel VVP Adaptive Noise Reduction" },
        { 0x0177, "Intel VVP Black Level Correction" },
        { 0x0178, "Intel VVP Vignette Correction" },
        { 0x0179, "Intel VVP White Balance Stats" },
        { 0x017a, "Intel VVP White Balance Correction" },
        { 0x017b, "Intel VVP Histogram Stats" },
        { 0x017c, "Intel VVP Unsharp Masking Filter" },
        { 0x017d, "Intel VVP 1D Lut" },
        { 0x017e, "Intel VVP Text Box" },
        { 0x0180, "OmniTek SDI Eye Pattern" },
        { 0x0200, "Altera Clocked Video Input V2" },
        { 0x0201, "Altera Clocked Video Output" },
        { 0x0202, "OmniTek Audio Extract" },
        { 0x0203, "OmniTek Audio Embed" },
        { 0x0204, "OmniTek Ancillary Extract" },
        { 0x0205, "OmniTek Ancillary Embed" },
        { 0x0206, "MPEG Video Decoder" },
        { 0x0208, "I2C Controller" },
        { 0x0209, "Memory Page Controller" },
        { 0x020a, "Altera Avalon Video Switch" },
        { 0x020b, "Altera Video Resizer" },
        { 0x020c, "Altera Video Combiner" },
        { 0x020d, "Intel 16550 Compatible UART" },
        { 0x020e, "Intel Avalon I2C (Master)" },
        { 0x020f, "Intel SPI (3 Wire Serial)" },
        { 0x0210, "Intel PIO (Parallel I/O)" },
        { 0x0211, "Intel Generic Serial Flash Interface" },
        { 0x0212, "Intel Address Span Extender Control Interface" },
        { 0x0213, "Intel Address Span Extender Memory Interface" },
        { 0x0214, "Omni Intel HDMI 2.0 Rx Core" },
        { 0x0215, "Omni Intel HDMI 2.0 Tx Core" },
        { 0x0216, "Omni Intel HDMI 2.0 Rx PHY" },
        { 0x0217, "Omni Intel HDMI 2.0 Tx PHY" },
        { 0x0218, "2D-FIR II Intel FPGA IP" },
        { 0x0219, "Clipper II Intel FPGA IP" },
        { 0x021A, "Chroma Resampler II Intel FPGA IP" },
        { 0x021B, "Color Space Converter II Intel FPGA IP" },
        { 0x021C, "Clocked Video Input II Intel FPGA IP" },
        { 0x021D, "Clocked Video Output II Intel FPGA IP" },
        { 0x021E, "Deinterlacer II Intel FPGA IP" },
        { 0x021F, "Frame Buffer Shuffle Intel FPGA IP" },
        { 0x0220, "Gamma Corrector II Intel FPGA IP" },
        { 0x0221, "Configurable Guard Bands Intel FPGA IP" },
        { 0x0222, "Interlacer II Intel FPGA IP" },
        { 0x0223, "Mixer II Intel FPGA IP" },
        { 0x0224, "Packet Timeout Controller Intel FPGA IP" },
        { 0x0225, "Scaler II Intel FPGA IP" },
        { 0x0226, "Avalon-ST Video Stream Cleaner Intel FPGA IP" },
        { 0x0227, "Switch II Intel FPGA IP" },
        { 0x0228, "Test Pattern Generator II Intel FPGA IP" },
        { 0x0229, "Frame Buffer II Intel FPGA IP" },
        { 0x022A, "Warp Lite Intel FPGA IP" },
        { 0x022C, "Intel VVP 2D-Fir Filter" },
        { 0x022D, "Intel VVP Clipper" },
        { 0x022E, "Intel VVP Chroma Resampler" },
        { 0x022F, "Intel VVP Color Space Converter" },
        { 0x0230, "Intel VVP Gamma Corrector" },
        { 0x0231, "Intel VVP Configurable Guard Bands" },
        { 0x0232, "Intel VVP Interlacer" },
        { 0x0233, "Intel VVP Mixer" },
        { 0x0234, "Intel VVP Scaler" },
        { 0x0235, "Intel VVP Switch" },
        { 0x0236, "Intel VVP Test Pattern Generator" },
        { 0x0237, "Intel VVP Frame Buffer" },
        { 0x0238, "Avalon I2C (Master) Intel FPGA IP" },
        { 0x0239, "Intel VVP Pixels in Parallel Converter" },
        { 0x023A, "Intel VVP Deinterlacer" },
        { 0x023B, "Intel VVP Color Plane Manager" },
        { 0x023C, "Intel VVP Fifo" },
        { 0x023D, "Intel VVP Protocol converter" },
        { 0x023E, "Intel VVP Cleaner" },
        { 0x023F, "Intel VVP Chroma Key" },
        { 0x0240, "Intel VVP CV 2 FR" },
        { 0x0241, "Intel VVP FR 2 CV" },
        { 0x0242, "Intel VVP FR 2 LITE" },
        { 0x0243, "Intel VVP VTIMING" },
        { 0x0244, "Intel VVP CVO" },
        { 0x0245, "Intel VVP Remosaic" },
        { 0x0246, "Intel VVP Demosaic" },
        { 0x0247, "Intel VVP Genlock Controller" },
        { 0x0248, "Intel VVP Snoop" },
        { 0x0249, "Intel VVP Frame Writer" },
        { 0x024A, "Intel VVP Frame Reader" },
        { 0x024B, "Intel VVP Timeout" },
        { 0x024C, "Intel VVP Bits Per Color Sample Adapter" },
        { 0x024D, "Intel APS Audio to Axi4Stream Converter" },
        { 0x024E, "Intel APS Axi4Stream to Audio Converter" },
        { 0x024F, "Intel APS audio test pattern generator" },
        { 0x0250, "Intel APS I2S" },
        { 0x0251, "Intel APS Volume Control" },
        { 0x0252, "Intel VVP Advanced Test Pattern Generator" },
        { 0x0253, "Intel VVP Metapacket Inserter" },
        { 0x0254, "Intel VVP Frame Buffer Shuffler" },
        { 0x0255, "Intel VVP Exposure Fusion" },
        { 0x0256, "Altera VVP Throttle" },
        { 0x0257, "Altera VVP Alpha Channel Generator" },
        { 0x0258, "Altera VVP Region of Interest" },
        { 0x0259, "Altera VVP DRM Adapter" },
        { 0x0300, "OmniTek HDMI Rx Input (XSVI) V2" },
        { 0x0301, "OmniTek HDMI Tx Output (XSVI) V2" },
        { 0x0302, "OmniTek SDI Rx Decoder (XSVI) V3" },
        { 0x0303, "OmniTek SDI Tx Encoder (XSVI) V2" },
        { 0x0304, "OmniTek AXI4-Streaming Cropper" },
        { 0x0305, "OmniTek AXI4-Streaming Video 2D-LUT" },
        { 0x0306, "OmniTek AXI4 Multi-Ported Video DMA V3" },
        { 0x0307, "OmniTek AXI4 OSVP" },
        { 0x0308, "OmniTek AXI4 Deinterlacer" },
        { 0x0309, "OmniTek AXI4-Streaming Video Resizer" },
        { 0x030a, "OmniTek AXI4 Generic Reset/IRQ Controller" },
        { 0x030b, "OmniTek AXI4-Streaming Colourspace Converter V2" },
        { 0x030c, "OmniTek AXI4-Streaming Video Overlay Generator" },
        { 0x030d, "OmniTek XSVI to AXIS Crosspoint video switch V2" },
        { 0x030e, "OmniTek XSVI Colourspace converter" },
        { 0x030f, "OmniTek Video Timebase Generator" },
        { 0x0310, "OmniTek Generic Line Pattern Generator" },
        { 0x0311, "OmniTek AXI4S Video Timing/Data Merger" },
        { 0x0312, "OmniTek XSVI SDI Analyzer V3" },
        { 0x0313, "OmniTek MSVC Multi-Stream-Video-Cropper" },
        { 0x0314, "OmniTek 4K-Video Interleaver" },
        { 0x0315, "OmniTek AXI4S video crosspoint V2" },
        { 0x0316, "OmniTek Jitter Measurement Core V2" },
        { 0x0317, "OmniTek Jitter Inserter Core" },
        { 0x0318, "OmniTek Framesync System Crosspoint" },
        { 0x0319, "OmniTek 16 Channel Video Combiner V4" },
        { 0x031a, "OmniTek 2k to 4k pixel doubler/stretcher (Row interleaved)" },
        { 0x031b, "OmniTek SDI Physical Generator" },
        { 0x031c, "OmniTek SDI RVF Unpacker" },
        { 0x031d, "OmniTek SDI RVF Packer" },
        { 0x031e, "OmniTek Ultra Video Effects" },
        { 0x031f, "OmniTek Video Analyzer V3" },
        { 0x0320, "OmniTek Video Generator V3" },
        { 0x0321, "OmniTek AXI-S Splitter (for Display Port MST mode)" },
        { 0x0322, "OmniTek Chroma 422 to 444 Upsampler" },
        { 0x0323, "OmniTek Interlacer" },
        { 0x0324, "OmniTek Noise Filter" },
        { 0x0325, "OmniTek Vid2DP (converts XSVI to Display Port MST Mode)" },
        { 0x0326, "OmniTek Generic MMCM controller" },
        { 0x0327, "OmniTek Gamma LUT" },
        { 0x0328, "OmniTek AXIS n to m pixel/clk converter" },
        { 0x0329, "OmniTek AXIS fifo monitor" },
        { 0x032a, "OmniTek Chroma 444 to 422 Downsampler" },
        { 0x032b, "OmniTek Generic FPGA Version Identifier" },
        { 0x032c, "OmniTek SPI Controller" },
        { 0x032d, "OmniTek Generic Video Frame Buffer V3" },
        { 0x032e, "OmniTek External Fan Control and Sensor" },
        { 0x032f, "OmniTek Video Cursor" },
        { 0x0330, "OmniTek Test Pattern Generator" },
        { 0x0331, "OmniTek Video Overlay II" },
        { 0x0332, "OmniTek Genlock Router" },
        { 0x0333, "OmniTek GTX Debug" },
        { 0x0334, "OmniTek DownScaler 4k2k" },
        { 0x0335, "OmniTek DP EDID" },
        { 0x0336, "OmniTek Waveforms" },
        { 0x0337, "OmniTek Scalable Warp Processor" },
        { 0x0338, "OmniTek Warp Regs" },
        { 0x0339, "OmniTek Minipic Generator" },
        { 0x033a, "OmniTek Audio Crosspoint V2" },
        { 0x033b, "OmniTek AXIS Clean Switch" },
        { 0x033c, "OmniTek AXIS Repacker" },
        { 0x033d, "OmniTek RVF AXIS Unpacker" },
        { 0x033e, "OmniTek SDI RVF-Axis Deskewer" },
        { 0x033f, "OmniTek AXI-Sequencer" },
        { 0x0340, "OmniTek V-by-1 Tx" },
        { 0x0341, "OmniTek V-by-1 Rx" },
        { 0x0342, "OmniTek V-by-1 PHY" },
        { 0x0344, "OmniTek LVDS Transmitter" },
        { 0x0345, "OmniTek LVDS Receiver" },
        { 0x0346, "OmniTek LVDS Merge" },
        { 0x0347, "OmniTek LVDS Unpacker" },
        { 0x0348, "OmniTek DP Tx" },
        { 0x0349, "OmniTek DP Rx" },
        { 0x034a, "OmniTek DP PHY" },
        { 0x034c, "OmniTek Image Signal Processor (ISP)" },
        { 0x034d, "OmniTek Projector Blend" },
        { 0x034e, "OmniTek FPGA Configuration Controller" },
        { 0x034f, "OmniTek License" },
        { 0x0350, "OmniTek LMH1981" },
        { 0x0351, "OmniTek Warp Genlock" },
        { 0x0352, "OmniTek Warp Debug" },
        { 0x0353, "OmniTek Page Controller" },
        { 0x0354, "OmniTek Ultrascale GTH Debug" },
        { 0x0355, "Omnitek Text Overlay" },
        { 0x0356, "Omnitek RFC4175 Axis to Ethernet TX" },
        { 0x0357, "Omnitek RFC4175 Ethernet RX to Axis" },
        { 0x0358, "Xilinx Owned AXI_1G_Ethernet_Subsystem" },
        { 0x0359, "Omnitek Warp I2C Fix" },
        { 0x035a, "OmniTek HDLC Tx" },
        { 0x035b, "OmniTek HDLC Rx" },
        { 0x035c, "Omnitek License Mux" },
        { 0x035d, "Omnitek Mapped Memory" },
        { 0x035e, "Omnitek Projector Test Pattern Generator" },
        { 0x035f, "Omnitek I2C Master" },
        { 0x0360, "Omnitek Warp OSD" },
        { 0x0362, "Omnitek MPVDMA VCU encoder video formatter" },
        { 0x0363, "Omnitek MPVDMA VCU decoder video formatter" },
        { 0x0364, "Omnitek I2S Tx" },
        { 0x0365, "Omnitek I2S Rx" },
        { 0x0366, "Omnitek I2C Repeater" },
        { 0x0367, "Omnitek Wireframe" },
        { 0x0368, "Omnitek 3D LUT" },
        { 0x0369, "Omnitek Warp Mesh" },
        { 0x0370, "Omnitek Chroma Down-Sampler 422 to 420" },
        { 0x0372, "Omnitek Chroma Up-Sampler 420 to 422" },
        { 0x0375, "OmniTek Contrast Enhancement Engine" },
        { 0x0381, "Omnitek external fsync generator" },
        { 0x0382, "Omnitek Soft Genlock" },
        { 0x0383, "OmniTek Audio Extract" },
        { 0x0384, "OmniTek Audio Embed" },
        { 0x0386, "OmniTek VbyOne TX output shim" },
        { 0x0388, "OmniTek PPMs" },
        { 0x0389, "OmniTek Demosaic Filter" },
        { 0x038a, "OmniTek Mailbox" },
        { 0x038c, "OmniTek Jitter Inserter (External IC) Core" },
        { 0x038d, "OmniTek AXIS Stall-Protection" },
        { 0x038e, "OmniTek sync generator" },
        { 0x0390, "OmniTek Wipe Generator" },
        { 0x0391, "Omnitek HDMI 2.0 Tx" },
        { 0x0392, "OmniTek Stream Combiner" },
        { 0x0394, "OmniTek SPI to Video" },
        { 0x0395, "OmniTek HDMI 2.0 Rx Core" },
        { 0x0396, "OmniTek HDMI 2.0 Phy V2" },
        { 0x0398, "Omni Line By Line" },
        { 0x039d, "OmniTek Disparity Adjust" },
        { 0x039e, "OmniTek HDA Controller" },
        { 0x039f, "OmniTek axis debug" },
        { 0x03a0, "OmniTek tuser delta" },
        { 0x03a1, "Omnitek Luma LUT" },
        { 0x03a2, "Omnitek DPU" },
        { 0x03a3, "Omnitek Axis Latency" },
        { 0x03a4, "Omnitek Message Mailbox" },
        { 0x03a5, "Omnitek MADI Tx" },
        { 0x03a6, "Omnitek MADI Rx" },
        { 0x03a7, "Omnitek Audio DMA" },
        { 0x03a8, "Omnitek Bayer TPG" },
        { 0x03a9, "Omnitek AES3 Tx" },
        { 0x03aa, "Omnitek AES3 Rx" },
        { 0x03ab, "Omnitek Audio Volume" },
        { 0x03ac, "Omnitek Control DPRAM" },
        { 0x03ad, "Omnitek Flash Controller" },
        { 0x03ae, "Omnitek Audio Clock Generator" },
        { 0x03b0, "OmniTek X2 Non-linear Resize" },
        { 0x03b1, "Omnitek MPVDMA pointer control" },
        { 0x03b2, "Omnitek Frame Cleaner" },
        { 0x03b5, "Intel coreDLA" },
        { 0x03b6, "Intel CoreDLA Layout Transform" },
        { 0x03bb, "Intel CoreDLA Stream Controller" },
        { 0x03bc, "Intel FSync Generator" },
        { 0x03bd, "Omnitek Axis to CV Converter" },
        { 0x03be, "Omnitek Low Latency CV to CV module" },
        { 0x03c3, "Omnitek Pixel Interleaver used for 3D Side By Side Display" },
        { 0x03c5, "Omnitek Chroma Key" },
        { 0x03c6, "Omnitek VCXO Control" },
        { 0x03c7, "Omnitek Axi GPIO" },
        { 0x03c8, "Omnitek Axi Throttle" },
        { 0x03cc, "Omnitek FPGA Status" },
        { 0x03e8, "Intel Simple Mailbox Sender" },
        { 0x03e9, "Intel Simple Mailbox Receiver" },
        { 0x03eC, "Intel On-Chip Memory II (RAM or ROM)" },
        { 0x0400, "Xilinx Owned AXI_OSD (on-screen-display)" },
        { 0x0401, "Xilinx Owned AXI_VTC (video timing generator)" },
        { 0x0402, "Xilinx Owned AXI_VDMA (video dma engine)" },
        { 0x0403, "Xilinx Owned DisplayPort Tx SubSystem" },
        { 0x0404, "Xilinx Owned DisplayPort Rx SubSystem" },
        { 0x0405, "Xilinx Owned AXI_GPIO" },
        { 0x0406, "Xilinx Owned AXI_IIC Controller" },
        { 0x0407, "OmniTek Pixel Doubler" },
        { 0x0408, "Xilinx Owned HDMI 2.0 Rx Decoder" },
        { 0x0409, "Xilinx Owned HDMI 2.0 Tx Encoder" },
        { 0x040a, "Xilinx Owned HDMI 2.0 GT" },
        { 0x040b, "Xilinx Owned HDMI 2.0 VPG" },
        { 0x040c, "Xilinx Owned HDMI 2.0 audio pattern generator" },
        { 0x040d, "Xilinx Owned general clock wizard with AXI port" },
        { 0x040e, "Xilinx Owned HDMI 2.0 ACR control" },
        { 0x040f, "Xilinx Owned microblaze interrupt controller" },
        { 0x0410, "OmniTek ROI" },
        { 0x0411, "Xilinx Owned AXI_SPI controller" },
        { 0x0412, "Xilinx Owned AXI_UARTLITE controller" },
        { 0x0413, "Xilinx Owned DisplayPort PHY (video phy)" },
        { 0x0414, "Xilinx Owned AXI_UART16550 controller" },
        { 0x0415, "Xilinx Owned DP EDID controller" },
        { 0x0416, "Xilinx Owned XADC controller" },
        { 0x0450, "Intel HDMI 2.1 Rx Core" },
        { 0x0451, "Intel HDMI 2.1 Tx Core" },
        { 0x0452, "Intel HDMI 2.1 Rx PHY" },
        { 0x0453, "Intel HDMI 2.1 Tx PHY" },
        { 0x0454, "Intel HDMI 2.0 Rx Core" },
        { 0x0455, "Intel HDMI 2.0 Tx Core" },
        { 0x0456, "Intel HDMI 2.0 Rx PHY" },
        { 0x0457, "Intel HDMI 2.0 Tx PHY" },
        { 0x0458, "Intel HDMI 2.0 I2C" },
        };
        return capabilityNames;
    }
} // namespace Hapi
