/*******************************************************************************
Copyright (C) Altera Corporation

This code and the related documents are Altera copyrighted materials and your
use of them is governed by the express license under which they were provided to
you ("License"). This code and the related documents are provided as is, with no
express or implied warranties other than those that are expressly stated in the
License.
*******************************************************************************/

/*
 ***** THIS FILE IS AUTO-GENERATED DO NOT MODIFY *****
 * Generated 2026-06-23 @ 15:57:38
 */

#pragma once

namespace Hapi
{
    enum class FPGA_CAPABILITY : uint32_t
    {
        NONE = 0x0000, // Placeholder
        fpga = 0x0010, // Legacy name for: Timer Capability V2
        OmniTimer = 0x0010, // Timer Capability V2
        // Missing name for 0x0012 = OmniTek Altera Video Input V3
        // Missing name for 0x0013 = OmniTek Altera Video Output V3
        OmniAlteraGenericInterrupt = 0x0014, // OmniTek Altera Generic Interrupt
        MDMA = 0x0102, // Legacy name for: Bi-Directional Data MDMA V5
        OmniDataBiMDMA = 0x0102, // Bi-Directional Data MDMA V5
        FDMA = 0x0104, // Legacy name for: Data In FDMA V5
        OmniDataInFDMA = 0x0104, // Data In FDMA V5
        OmniDataOutFDMA = 0x0105, // Data Out FDMA
        OmniVideoInFDMA = 0x0114, // Video In FDMA V5
        OmniVideoOutFDMA = 0x0115, // Video Out FDMA
        OmniPacketInFDMA = 0x0134, // Packet In FDMA
        OmniPacketOutFDMA = 0x0135, // Packet Out FDMA
        intel_vvp_tmo = 0x0163, // Intel VVP Tone Mapping Operator
        intel_vvp_3d_lut = 0x0165, // Intel VVP 3D Lut
        IntelOSWP = 0x016F, // Intel Scalable Warp Processor
        intel_vvp_cvi = 0x0170, // Intel VVP Clocked Video In
        intel_vvp_generic_crosspoint = 0x0171, // Intel VVP Generic Crosspoint
        intel_vvp_genlock_router = 0x0172, // Intel VVP Genlock Router
        intel_vvp_cvs_2_vpplite = 0x0173, // Intel VVP CVI_2_VVPLite
        intel_vvp_black_level_stats = 0x0174, // Intel VVP Black Level Stats
        intel_vvp_defective_pixel_correction = 0x0175, // Intel VVP Defective Pixel Correction
        intel_vvp_adaptive_noise_reduction = 0x0176, // Intel VVP Adaptive Noise Reduction
        intel_vvp_black_level_correction = 0x0177, // Intel VVP Black Level Correction
        intel_vvp_vignette_correction = 0x0178, // Intel VVP Vignette Correction
        intel_vvp_white_balance_stats = 0x0179, // Intel VVP White Balance Stats
        intel_vvp_white_balance_correction = 0x017a, // Intel VVP White Balance Correction
        intel_vvp_histogram_stats = 0x017b, // Intel VVP Histogram Stats
        intel_vvp_unsharp_masking_filter = 0x017c, // Intel VVP Unsharp Masking Filter
        intel_vvp_1d_lut = 0x017d, // Intel VVP 1D Lut
        intel_vvp_text_box = 0x017e, // Intel VVP Text Box
        EyeScan = 0x0180, // Legacy name for: OmniTek SDI Eye Pattern
        OmniEyeScanDMA = 0x0180, // OmniTek SDI Eye Pattern
        AlteraClockedVideoIn = 0x0200, // Altera Clocked Video Input V2
        AlteraClockedVideoOut = 0x0201, // Altera Clocked Video Output
        OmniTekAudioExtract = 0x0202, // OmniTek Audio Extract
        OmniTekAudioEmbed = 0x0203, // OmniTek Audio Embed
        OmniTekAncExtract = 0x0204, // OmniTek Ancillary Extract
        OmniTekAncEmbed = 0x0205, // OmniTek Ancillary Embed
        // Missing name for 0x0206 = MPEG Video Decoder
        OmniTekI2cController = 0x0208, // I2C Controller
        // Missing name for 0x0209 = Memory Page Controller
        // Missing name for 0x020a = Altera Avalon Video Switch
        // Missing name for 0x020b = Altera Video Resizer
        // Missing name for 0x020c = Altera Video Combiner
        Intel16550Uart = 0x020d, // Intel 16550 Compatible UART
        IntelI2CMaster = 0x020e, // Intel Avalon I2C (Master)
        IntelSPICtrl = 0x020f, // Intel SPI (3 Wire Serial)
        IntelParallelIO = 0x0210, // Intel PIO (Parallel I/O)
        IntelSerialFlash = 0x0211, // Intel Generic Serial Flash Interface
        IntelAddressSpanExtCtrl = 0x0212, // Intel Address Span Extender Control Interface
        IntelAddressSpanExtMem = 0x0213, // Intel Address Span Extender Memory Interface
        OmniIntelHDMI20Rx = 0x0214, // Omni Intel HDMI 2.0 Rx Core
        OmniIntelHDMI20Tx = 0x0215, // Omni Intel HDMI 2.0 Tx Core
        OmniIntelHDMI20RxPhy = 0x0216, // Omni Intel HDMI 2.0 Rx PHY
        OmniIntelHDMI20TxPhy = 0x0217, // Omni Intel HDMI 2.0 Tx PHY
        alt_vip_cl_2dfir = 0x0218, // 2D-FIR II Intel FPGA IP
        alt_vip_cl_clp = 0x0219, // Clipper II Intel FPGA IP
        alt_vip_cl_crs  = 0x021A, // Chroma Resampler II Intel FPGA IP
        alt_vip_cl_csc = 0x021B, // Color Space Converter II Intel FPGA IP
        alt_vip_cl_cvi = 0x021C, // Clocked Video Input II Intel FPGA IP
        alt_vip_cl_cvo = 0x021D, // Clocked Video Output II Intel FPGA IP
        alt_vip_cl_dil = 0x021E, // Deinterlacer II Intel FPGA IP
        alt_vip_cl_fb_switch = 0x021F, // Frame Buffer Shuffle Intel FPGA IP
        alt_vip_cl_gamma_corrector = 0x0220, // Gamma Corrector II Intel FPGA IP
        alt_vip_cl_guard_bands = 0x0221, // Configurable Guard Bands Intel FPGA IP
        alt_vip_cl_interlacer = 0x0222, // Interlacer II Intel FPGA IP
        alt_vip_cl_mixer  = 0x0223, // Mixer II Intel FPGA IP
        alt_vip_cl_packet_closer = 0x0224, // Packet Timeout Controller Intel FPGA IP
        alt_vip_cl_scl = 0x0225, // Scaler II Intel FPGA IP
        alt_vip_cl_stream_cleaner = 0x0226, // Avalon-ST Video Stream Cleaner Intel FPGA IP
        alt_vip_cl_swi = 0x0227, // Switch II Intel FPGA IP
        alt_vip_cl_tpg = 0x0228, // Test Pattern Generator II Intel FPGA IP
        alt_vip_cl_vfb = 0x0229, // Frame Buffer II Intel FPGA IP
        alt_vip_cl_warp  = 0x022A, // Warp Lite Intel FPGA IP
        intel_vvp_2d_fir = 0x022C, // Intel VVP 2D-Fir Filter
        intel_vvp_clipper = 0x022D, // Intel VVP Clipper
        intel_vvp_chroma_resampler = 0x022E, // Intel VVP Chroma Resampler
        intel_vvp_color_space_conv = 0x022F, // Intel VVP Color Space Converter
        intel_vvp_gamma_corrector = 0x0230, // Intel VVP Gamma Corrector
        intel_vvp_guard_bands = 0x0231, // Intel VVP Configurable Guard Bands
        intel_vvp_interlacer = 0x0232, // Intel VVP Interlacer
        intel_vvp_mixer = 0x0233, // Intel VVP Mixer
        intel_vvp_scaler = 0x0234, // Intel VVP Scaler
        intel_vvp_switch = 0x0235, // Intel VVP Switch
        intel_vvp_test_pattern_gen = 0x0236, // Intel VVP Test Pattern Generator
        intel_vvp_frame_buffer = 0x0237, // Intel VVP Frame Buffer
        altera_avalon_i2c = 0x0238, // Avalon I2C (Master) Intel FPGA IP
        intel_vvp_pip_conv = 0x0239, // Intel VVP Pixels in Parallel Converter
        intel_vvp_deinterlacer = 0x023A, // Intel VVP Deinterlacer
        intel_vvp_cpm = 0x023B, // Intel VVP Color Plane Manager
        intel_vvp_fifo = 0x023C, // Intel VVP Fifo
        intel_vvp_protocol_conv = 0x023D, // Intel VVP Protocol converter
        intel_vvp_cleaner = 0x023E, // Intel VVP Cleaner
        intel_vvp_chroma_key = 0x023F, // Intel VVP Chroma Key
        intel_vvp_cv2fr = 0x0240, // Intel VVP CV 2 FR
        intel_vvp_fr2cv = 0x0241, // Intel VVP FR 2 CV
        intel_vvp_fr2lite = 0x0242, // Intel VVP FR 2 LITE
        intel_vvp_vtiming = 0x0243, // Intel VVP VTIMING
        intel_vvp_cvo = 0x0244, // Intel VVP CVO
        intel_vvp_remosaic = 0x0245, // Intel VVP Remosaic
        intel_vvp_demosaic = 0x0246, // Intel VVP Demosaic
        intel_vvp_genlock_controller = 0x0247, // Intel VVP Genlock Controller
        intel_vvp_snoop = 0x0248, // Intel VVP Snoop
        intel_vvp_vfw = 0x0249, // Intel VVP Frame Writer
        intel_vvp_vfr = 0x024A, // Intel VVP Frame Reader
        intel_vvp_timeout = 0x024B, // Intel VVP Timeout
        intel_vvp_pixel_adapter = 0x024C, // Intel VVP Bits Per Color Sample Adapter
        intel_aps_audio2axi = 0x024D, // Intel APS Audio to Axi4Stream Converter
        intel_aps_axi2audio = 0x024E, // Intel APS Axi4Stream to Audio Converter
        intel_aps_atpg = 0x024F, // Intel APS audio test pattern generator
        intel_aps_i2s = 0x0250, // Intel APS I2S
        intel_aps_volume_control = 0x0251, // Intel APS Volume Control
        intel_vvp_adv_tpg = 0x0252, // Intel VVP Advanced Test Pattern Generator
        intel_vvp_metapacket_inserter = 0x0253, // Intel VVP Metapacket Inserter
        intel_vvp_frame_buffer_shuffler = 0x0254, // Intel VVP Frame Buffer Shuffler
        intel_vvp_exposure_fusion = 0x0255, // Intel VVP Exposure Fusion
        altera_vvp_throttle = 0x0256, // Altera VVP Throttle
        altera_vvp_alpha_gen = 0x0257, // Altera VVP Alpha Channel Generator
        altera_vvp_roi = 0x0258, // Altera VVP Region of Interest
        altera_vvp_drm_adapter = 0x0259, // Altera VVP DRM Adapter
        HDMI_Rx = 0x0300, // Legacy name for: OmniTek HDMI Rx Input (XSVI) V2
        HDMI_Tx = 0x0301, // Legacy name for: OmniTek HDMI Tx Output (XSVI) V2
        SDI_Rx = 0x0302, // Legacy name for: OmniTek SDI Rx Decoder (XSVI) V3
        SDI_Tx = 0x0303, // Legacy name for: OmniTek SDI Tx Encoder (XSVI) V2
        // Missing name for 0x0304 = OmniTek AXI4-Streaming Cropper
        // Missing name for 0x0305 = OmniTek AXI4-Streaming Video 2D-LUT
        OmniTekMPVDMA = 0x0306, // OmniTek AXI4 Multi-Ported Video DMA V3
        OSVP = 0x0307, // Legacy name for: OmniTek AXI4 OSVP
        // Missing name for 0x0308 = OmniTek AXI4 Deinterlacer
        OmniTekStreamingVideoResizer = 0x0309, // OmniTek AXI4-Streaming Video Resizer
        // Missing name for 0x030a = OmniTek AXI4 Generic Reset/IRQ Controller
        AXI_CSC = 0x030b, // Legacy name for: OmniTek AXI4-Streaming Colourspace Converter V2
        Overlay = 0x030c, // Legacy name for: OmniTek AXI4-Streaming Video Overlay Generator
        XPoint = 0x030d, // Legacy name for: OmniTek XSVI to AXIS Crosspoint video switch V2
        XSVI_CSC = 0x030e, // Legacy name for: OmniTek XSVI Colourspace converter
        VTiming = 0x030f, // Legacy name for: OmniTek Video Timebase Generator
        OmniLinePatternGenerator = 0x0310, // OmniTek Generic Line Pattern Generator
        // Missing name for 0x0311 = OmniTek AXI4S Video Timing/Data Merger
        SDI_Analyzer = 0x0312, // Legacy name for: OmniTek XSVI SDI Analyzer V3
        // Missing name for 0x0313 = OmniTek MSVC Multi-Stream-Video-Cropper
        // Missing name for 0x0314 = OmniTek 4K-Video Interleaver
        OmniXpnt = 0x0315, // Legacy name for: OmniTek AXI4S video crosspoint V2
        JitterMeasure = 0x0316, // Legacy name for: OmniTek Jitter Measurement Core V2
        JitterInsert = 0x0317, // Legacy name for: OmniTek Jitter Inserter Core
        FrameSyncSelect = 0x0318, // Legacy name for: OmniTek Framesync System Crosspoint
        Combiner = 0x0319, // Legacy name for: OmniTek 16 Channel Video Combiner V4
        // Missing name for 0x031a = OmniTek 2k to 4k pixel doubler/stretcher (Row interleaved)
        Phy_insert = 0x031b, // Legacy name for: OmniTek SDI Physical Generator
        SDI_Unpacker = 0x031c, // Legacy name for: OmniTek SDI RVF Unpacker
        SDI_Packer = 0x031d, // Legacy name for: OmniTek SDI RVF Packer
        VideoEffects = 0x031e, // Legacy name for: OmniTek Ultra Video Effects
        VideoAnalyzer = 0x031f, // Legacy name for: OmniTek Video Analyzer V3
        Generator = 0x0320, // Legacy name for: OmniTek Video Generator V3
        MST_Ctrl = 0x0321, // Legacy name for: OmniTek AXI-S Splitter (for Display Port MST mode)
        // Missing name for 0x0322 = OmniTek Chroma 422 to 444 Upsampler
        OmniInterlacer = 0x0323, // Legacy name for: OmniTek Interlacer
        // Missing name for 0x0324 = OmniTek Noise Filter
        // Missing name for 0x0325 = OmniTek Vid2DP (converts XSVI to Display Port MST Mode)
        MMCM = 0x0326, // Legacy name for: OmniTek Generic MMCM controller
        // Missing name for 0x0327 = OmniTek Gamma LUT
        // Missing name for 0x0328 = OmniTek AXIS n to m pixel/clk converter
        // Missing name for 0x0329 = OmniTek AXIS fifo monitor
        OmniChromaDown = 0x032a, // Legacy name for: OmniTek Chroma 444 to 422 Downsampler
        OmniVersion = 0x032b, // Legacy name for: OmniTek Generic FPGA Version Identifier
        OmniSPIController = 0x032c, // OmniTek SPI Controller
        OmniFrameBuffer = 0x032d, // Legacy name for: OmniTek Generic Video Frame Buffer V3
        OmniFan = 0x032e, // Legacy name for: OmniTek External Fan Control and Sensor
        OmniCursor = 0x032f, // Legacy name for: OmniTek Video Cursor
        OmniTestPattern = 0x0330, // Legacy name for: OmniTek Test Pattern Generator
        OmniOverlay2 = 0x0331, // Legacy name for: OmniTek Video Overlay II
        OmniGenlock = 0x0332, // Legacy name for: OmniTek Genlock Router
        OmniTekGTXDebug = 0x0333, // OmniTek GTX Debug
        OmniDownScaler4k2k = 0x0334, // Legacy name for: OmniTek DownScaler 4k2k
        OmniDPEDID = 0x0335, // Legacy name for: OmniTek DP EDID
        OmniWfm = 0x0336, // Legacy name for: OmniTek Waveforms
        OmniTekOSWP = 0x0337, // Legacy name for: OmniTek Scalable Warp Processor
        OmniTekWarpRegs = 0x0338, // Legacy name for: OmniTek Warp Regs
        OmniTekMiniPic = 0x0339, // Legacy name for: OmniTek Minipic Generator
        OmniTekAudioCrossPoint = 0x033a, // Legacy name for: OmniTek Audio Crosspoint V2
        OmniTekAXISCleanSwitch = 0x033b, // OmniTek AXIS Clean Switch
        OmniTekAxisRepacker = 0x033c, // OmniTek AXIS Repacker
        OmniTekRVFUnpacker = 0x033d, // OmniTek RVF AXIS Unpacker
        OmniTekSDIDeskew = 0x033e, // OmniTek SDI RVF-Axis Deskewer
        OmniTekAXISequencer = 0x033f, // OmniTek AXI-Sequencer
        OmniTekVx1Tx = 0x0340, // OmniTek V-by-1 Tx
        OmniTekVx1Rx = 0x0341, // OmniTek V-by-1 Rx
        OmniTekVx1PHY = 0x0342, // OmniTek V-by-1 PHY
        // Missing name for 0x0344 = OmniTek LVDS Transmitter
        // Missing name for 0x0345 = OmniTek LVDS Receiver
        OmniLVDSMerge = 0x0346, // OmniTek LVDS Merge
        OmniLVDSUnpacker = 0x0347, // OmniTek LVDS Unpacker
        // Missing name for 0x0348 = OmniTek DP Tx
        // Missing name for 0x0349 = OmniTek DP Rx
        // Missing name for 0x034a = OmniTek DP PHY
        OmniISP = 0x034c, // OmniTek Image Signal Processor (ISP)
        OmniProjectorBlend = 0x034d, // OmniTek Projector Blend
        OmniFPGAConfigurationController = 0x034e, // OmniTek FPGA Configuration Controller
        OmniTekLicense = 0x034f, // OmniTek License
        // Missing name for 0x0350 = OmniTek LMH1981
        OmniTekWarpGenlock = 0x0351, // OmniTek Warp Genlock
        OmniTekWarpDebug = 0x0352, // OmniTek Warp Debug
        // Missing name for 0x0353 = OmniTek Page Controller
        OmniTekUltrascaleGTHDebug = 0x0354, // OmniTek Ultrascale GTH Debug
        OmniAxisText = 0x0355, // Omnitek Text Overlay
        OmniRFC4175Tx = 0x0356, // Omnitek RFC4175 Axis to Ethernet TX
        OmniRFC4175Rx = 0x0357, // Omnitek RFC4175 Ethernet RX to Axis
        XIL_AXI_1G_Ethernet = 0x0358, // Legacy name for: Xilinx Owned AXI_1G_Ethernet_Subsystem
        // Missing name for 0x0359 = Omnitek Warp I2C Fix
        // Missing name for 0x035a = OmniTek HDLC Tx
        // Missing name for 0x035b = OmniTek HDLC Rx
        OmniLicenseMux = 0x035c, // Omnitek License Mux
        // Missing name for 0x035d = Omnitek Mapped Memory
        OmniProjectorTPG = 0x035e, // Omnitek Projector Test Pattern Generator
        // Missing name for 0x035f = Omnitek I2C Master
        OmnitekWarpOSD = 0x0360, // Legacy name for: Omnitek Warp OSD
        OmniSplanarEncoder = 0x0362, // Omnitek MPVDMA VCU encoder video formatter
        OmniSplanarDecoder = 0x0363, // Omnitek MPVDMA VCU decoder video formatter
        OmniI2STx = 0x0364, // Omnitek I2S Tx
        OmniI2SRx = 0x0365, // Omnitek I2S Rx
        // Missing name for 0x0366 = Omnitek I2C Repeater
        // Missing name for 0x0367 = Omnitek Wireframe
        // Missing name for 0x0368 = Omnitek 3D LUT
        // Missing name for 0x0369 = Omnitek Warp Mesh
        OmniChromaDown422to420 = 0x0370, // Omnitek Chroma Down-Sampler 422 to 420
        OmniChromaUp420to422 = 0x0372, // Omnitek Chroma Up-Sampler 420 to 422
        OmniTMO = 0x0375, // OmniTek Contrast Enhancement Engine
        OmniExtFsyncGen = 0x0381, // Omnitek external fsync generator
        omnisoftgenlock = 0x0382, // Omnitek Soft Genlock
        OmniAudioExtract = 0x0383, // OmniTek Audio Extract
        OmniAudioEmbed = 0x0384, // OmniTek Audio Embed
        OmniVbyOneTX = 0x0386, // OmniTek VbyOne TX output shim
        OmniPPMs = 0x0388, // Legacy name for: OmniTek PPMs
        OmniDemosaic = 0x0389, // Legacy name for: OmniTek Demosaic Filter
        OmniMailbox = 0x038a, // Legacy name for: OmniTek Mailbox
        JitterInsertExt = 0x038c, // Legacy name for: OmniTek Jitter Inserter (External IC) Core
        // Missing name for 0x038d = OmniTek AXIS Stall-Protection
        // Missing name for 0x038e = OmniTek sync generator
        OmniWipeGen = 0x0390, // OmniTek Wipe Generator
        OmniHDMI20Tx = 0x0391, // Legacy name for: Omnitek HDMI 2.0 Tx
        OmniStreamCombiner = 0x0392, // Legacy name for: OmniTek Stream Combiner
        OmniSpiVideoDecoder = 0x0394, // Legacy name for: OmniTek SPI to Video
        OmniHDMI20Rx = 0x0395, // Legacy name for: OmniTek HDMI 2.0 Rx Core
        OmniHDMI20RX = 0x0395, // OmniTek HDMI 2.0 Rx Core
        OmniHDMI20Phy = 0x0396, // Legacy name for: OmniTek HDMI 2.0 Phy V2
        OmniHDMI20PHY = 0x0396, // OmniTek HDMI 2.0 Phy V2
        OmniLineByLine = 0x0398, // Omni Line By Line
        OmniDisparityAjust = 0x039d, // OmniTek Disparity Adjust
        OmniHDAController = 0x039e, // OmniTek HDA Controller
        OmniAxisDebug = 0x039f, // OmniTek axis debug
        OmniTUserDelta = 0x03a0, // OmniTek tuser delta
        OmniLumaLut = 0x03a1, // Omnitek Luma LUT
        OmniDPU = 0x03a2, // Omnitek DPU
        OmniAxisLatency = 0x03a3, // Omnitek Axis Latency
        OmniMsgMailbox = 0x03a4, // Omnitek Message Mailbox
        OmniMadiTx = 0x03a5, // Omnitek MADI Tx
        OmniMadiRx = 0x03a6, // Omnitek MADI Rx
        OmniAudioDMA = 0x03a7, // Omnitek Audio DMA
        OmniBayerTPG = 0x03a8, // Omnitek Bayer TPG
        OmniAES3Tx = 0x03a9, // Omnitek AES3 Tx
        OmniAES3Rx = 0x03aa, // Omnitek AES3 Rx
        OmniAudioVol = 0x03ab, // Omnitek Audio Volume
        OmniCtlDPRAM = 0x03ac, // Omnitek Control DPRAM
        OmniFlashCtrl = 0x03ad, // Omnitek Flash Controller
        OmniAudioClkGen = 0x03ae, // Omnitek Audio Clock Generator
        OmniX2NonlinearResize = 0x03b0, // OmniTek X2 Non-linear Resize
        OmniPtrCtrl = 0x03b1, // Omnitek MPVDMA pointer control
        OmniFrameCleaner = 0x03b2, // Omnitek Frame Cleaner
        IntelCoreDLA = 0x03b5, // Intel coreDLA
        IntelCoreDLALayoutTransform = 0x03b6, // Intel CoreDLA Layout Transform
        IntelCoreDLAStreamController = 0x03bb, // Intel CoreDLA Stream Controller
        IntelFSyncGen = 0x03bc, // Intel FSync Generator
        OmniAxi4s2CV = 0x03bd, // Omnitek Axis to CV Converter
        Omni_CV_to_CV = 0x03be, // Omnitek Low Latency CV to CV module
        OmniSideBySide = 0x03c3, // Omnitek Pixel Interleaver used for 3D Side By Side Display
        OmniChromaKey = 0x03c5, // Omnitek Chroma Key
        OmniVcxoControl = 0x03c6, // Omnitek VCXO Control
        OmniAxiGpio = 0x03c7, // Omnitek Axi GPIO
        OmniAxiThrottle = 0x03c8, // Omnitek Axi Throttle
        OmniFpgaStatus = 0x03cc, // Omnitek FPGA Status
        IntelMailboxSender = 0x03e8, // Intel Simple Mailbox Sender
        IntelMailboxReceiver = 0x03e9, // Intel Simple Mailbox Receiver
        IntelOnChipMemII = 0x03eC, // Intel On-Chip Memory II (RAM or ROM)
        // Missing name for 0x0400 = Xilinx Owned AXI_OSD (on-screen-display)
        // Missing name for 0x0401 = Xilinx Owned AXI_VTC (video timing generator)
        Xil_VDMA = 0x0402, // Legacy name for: Xilinx Owned AXI_VDMA (video dma engine)
        DisplayPort_Tx = 0x0403, // Legacy name for: Xilinx Owned DisplayPort Tx SubSystem
        DisplayPort_Rx = 0x0404, // Legacy name for: Xilinx Owned DisplayPort Rx SubSystem
        Xil_GPIO = 0x0405, // Legacy name for: Xilinx Owned AXI_GPIO
        Xil_IIC = 0x0406, // Legacy name for: Xilinx Owned AXI_IIC Controller
        OmniPixelDoubler = 0x0407, // Legacy name for: OmniTek Pixel Doubler
        // Missing name for 0x0408 = Xilinx Owned HDMI 2.0 Rx Decoder
        // Missing name for 0x0409 = Xilinx Owned HDMI 2.0 Tx Encoder
        // Missing name for 0x040a = Xilinx Owned HDMI 2.0 GT
        // Missing name for 0x040b = Xilinx Owned HDMI 2.0 VPG
        // Missing name for 0x040c = Xilinx Owned HDMI 2.0 audio pattern generator
        // Missing name for 0x040d = Xilinx Owned general clock wizard with AXI port
        // Missing name for 0x040e = Xilinx Owned HDMI 2.0 ACR control
        // Missing name for 0x040f = Xilinx Owned microblaze interrupt controller
        OmniROI = 0x0410, // Legacy name for: OmniTek ROI
        Xil_SPI = 0x0411, // Legacy name for: Xilinx Owned AXI_SPI controller
        Xil_AXI_UARTLITE = 0x0412, // Legacy name for: Xilinx Owned AXI_UARTLITE controller
        Xil_VPHY = 0x0413, // Legacy name for: Xilinx Owned DisplayPort PHY (video phy)
        Xil_AXI_UART16550 = 0x0414, // Legacy name for: Xilinx Owned AXI_UART16550 controller
        DP_EDID = 0x0415, // Legacy name for: Xilinx Owned DP EDID controller
        XADC_Controller = 0x0416, // Legacy name for: Xilinx Owned XADC controller
        IntelHDMI21Rx = 0x0450, // Intel HDMI 2.1 Rx Core
        IntelHDMI21Tx = 0x0451, // Intel HDMI 2.1 Tx Core
        IntelHDMI21RxPhy = 0x0452, // Intel HDMI 2.1 Rx PHY
        IntelHDMI21TxPhy = 0x0453, // Intel HDMI 2.1 Tx PHY
        IntelHDMI20Rx = 0x0454, // Intel HDMI 2.0 Rx Core
        IntelHDMI20Tx = 0x0455, // Intel HDMI 2.0 Tx Core
        IntelHDMI20RxPhy = 0x0456, // Intel HDMI 2.0 Rx PHY
        IntelHDMI20TxPhy = 0x0457, // Intel HDMI 2.0 Tx PHY
        IntelHDMI20TiI2c = 0x0458, // Intel HDMI 2.0 I2C
    };
} // namespace Hapi
