/*******************************************************************************
Copyright (C) Altera Corporation
 
This code and the related documents are Altera copyrighted materials and your
use of them is governed by the express license under which they were provided to
you ("License"). This code and the related documents are provided as is, with no
express or implied warranties other than those that are expressly stated in the
License.
*******************************************************************************/

#ifndef __INTEL_VVP_WARP_REGS_H__
#define __INTEL_VVP_WARP_REGS_H__


#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */

/* Offset added by the front-end slave interface */
#define INTEL_VVP_WARP_FRONT_END_IF_OFFSET 					(0x0180/4)

/* Size of a register block in 32bit words */
#define INTEL_VVP_WARP_REG_BLOCK_SIZE						(16)

/* Register map */
#define INTEL_VVP_WARP_REGMAP_BASE							(INTEL_VVP_WARP_FRONT_END_IF_OFFSET)
#define INTEL_VVP_WARP_CONFIG								(0)
#define INTEL_VVP_WARP_MEM_CONTROL							(3)
#define INTEL_VVP_WARP_CONFIG_EXT							(7)

#define INTEL_VVP_WARP_INPUT_BASE(i)						(INTEL_VVP_WARP_REGMAP_BASE+INTEL_VVP_WARP_REG_BLOCK_SIZE+INTEL_VVP_WARP_REG_BLOCK_SIZE*(i))
#define INTEL_VVP_WARP_INPUTS_SIZE							(INTEL_VVP_WARP_REG_BLOCK_SIZE*instance->num_inputs)
#define INTEL_VVP_WARP_INPUT_CONFIG							(0)
#define INTEL_VVP_WARP_INPUT_CONTROL						(1)
#define INTEL_VVP_WARP_INPUT_STATUS							(2)
#define INTEL_VVP_WARP_INPUT_RESOLUTION						(3)
#define INTEL_VVP_WARP_INPUT_OFFSET 						(4)
#define INTEL_VVP_WARP_INPUT_RAM     						(5)

#define INTEL_VVP_WARP_OUTPUT_BASE(i)						(INTEL_VVP_WARP_INPUT_BASE(0)+INTEL_VVP_WARP_INPUTS_SIZE+(INTEL_VVP_WARP_REG_BLOCK_SIZE*(i)))
#define INTEL_VVP_WARP_OUTPUTS_SIZE							(INTEL_VVP_WARP_REG_BLOCK_SIZE*instance->num_outputs)
#define INTEL_VVP_WARP_OUTPUT_CONFIG						(0)
#define INTEL_VVP_WARP_OUTPUT_CONTROL						(1)
#define INTEL_VVP_WARP_OUTPUT_STATUS						(2)
#define INTEL_VVP_WARP_OUTPUT_RESOLUTION					(3)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EXT					(4)
#define INTEL_VVP_WARP_OUTPUT_RAM							(5)
#define INTEL_VVP_WARP_OUTPUT_LATENCY						(6)

#define INTEL_VVP_WARP_ENGINE_BASE(i)						(INTEL_VVP_WARP_OUTPUT_BASE(0)+INTEL_VVP_WARP_OUTPUTS_SIZE+(INTEL_VVP_WARP_REG_BLOCK_SIZE*(i)))
#define INTEL_VVP_WARP_ENGINES_SIZE							(INTEL_VVP_WARP_REG_BLOCK_SIZE*instance->num_engines)
#define INTEL_VVP_WARP_ENGINE_CONFIG						(0)
#define INTEL_VVP_WARP_ENGINE_CONTROL						(1)
#define INTEL_VVP_WARP_ENGINE_STATUS						(2)
#define INTEL_VVP_WARP_ENGINE_COEF_CTRL						(3)
#define INTEL_VVP_WARP_ENGINE_GEOMETRY_START				(4)
#define INTEL_VVP_WARP_ENGINE_GEOMETRY_END					(5)
#define INTEL_VVP_WARP_ENGINE_RAM							(6)
#define INTEL_VVP_WARP_ENGINE_MESH_CTL						(7)

/* Debug measurement registers */
#define INTEL_VVP_WARP_DEBUG_REGION_SIZE					(INTEL_VVP_WARP_REG_BLOCK_SIZE)
#define INTEL_VVP_WARP_DEBUG_BASE							(INTEL_VVP_WARP_ENGINE_BASE(0)+INTEL_VVP_WARP_ENGINES_SIZE)
#define INTEL_VVP_WARP_DEBUG_SIZE							(INTEL_VVP_WARP_DEBUG_REGION_SIZE)
#define INTEL_VVP_WARP_DEBUG_MEM_WR_QUEUES0					(0)
#define INTEL_VVP_WARP_DEBUG_MEM_WR_QUEUES1					(1)
#define INTEL_VVP_WARP_DEBUG_MEM_RD_QUEUES0					(2)
#define INTEL_VVP_WARP_DEBUG_MEM_RD_QUEUES1					(3)
#define INTEL_VVP_WARP_DEBUG_MEM_RD_CYCLES					(8)
#define INTEL_VVP_WARP_DEBUG_MEM_WR_CYCLES					(9)
#define INTEL_VVP_WARP_DEBUG_MEM_STALL_CYCLES				(10)

#define INTEL_VVP_WARP_DEBUG_INPUT_BASE(i)					(INTEL_VVP_WARP_DEBUG_BASE+INTEL_VVP_WARP_DEBUG_SIZE+INTEL_VVP_WARP_DEBUG_REGION_SIZE*(i))
#define INTEL_VVP_WARP_DEBUG_INPUTS_SIZE					(INTEL_VVP_WARP_DEBUG_REGION_SIZE*instance->num_inputs)
#define INTEL_VVP_WARP_DEBUG_INPUT_FRAME_COUNT				(0)
#define INTEL_VVP_WARP_DEBUG_INPUT_FRAME_PERIOD				(1)
#define INTEL_VVP_WARP_DEBUG_INPUT_MEM_WRITES				(2)
#define INTEL_VVP_WARP_DEBUG_INPUT_MIPMAP_MEM_WRITES		(3)

#define INTEL_VVP_WARP_DEBUG_OUTPUT_BASE(i)					(INTEL_VVP_WARP_DEBUG_INPUT_BASE(0)+INTEL_VVP_WARP_DEBUG_INPUTS_SIZE+INTEL_VVP_WARP_DEBUG_REGION_SIZE*(i))
#define INTEL_VVP_WARP_DEBUG_OUTPUTS_SIZE					(INTEL_VVP_WARP_DEBUG_REGION_SIZE*instance->num_outputs)
#define INTEL_VVP_WARP_DEBUG_OUTPUT_FRAME_COUNT				(0)
#define INTEL_VVP_WARP_DEBUG_OUTPUT_FRAME_PERIOD			(1)

#define INTEL_VVP_WARP_DEBUG_ENGINE_BASE(i)					(INTEL_VVP_WARP_DEBUG_OUTPUT_BASE(0)+INTEL_VVP_WARP_DEBUG_OUTPUTS_SIZE+INTEL_VVP_WARP_DEBUG_REGION_SIZE*(i))
#define INTEL_VVP_WARP_DEBUG_ENGINES_SIZE					(INTEL_VVP_WARP_DEBUG_REGION_SIZE*instance->num_engines)
#define INTEL_VVP_WARP_DEBUG_ENGINE_FRAME_COUNT				(0)
#define INTEL_VVP_WARP_DEBUG_ENGINE_FRAME_PERIOD			(1)
#define INTEL_VVP_WARP_DEBUG_ENGINE_BUSY_CYCLES				(2)
#define INTEL_VVP_WARP_DEBUG_ENGINE_FRAME_DELAY				(3)
#define INTEL_VVP_WARP_DEBUG_ENGINE_RUN_STATUS				(4)
#define INTEL_VVP_WARP_DEBUG_ENGINE_CACHE_LOADS			    (5)

#define INTEL_VVP_WARP_DEBUG_SIZE_TOTAL						(INTEL_VVP_WARP_DEBUG_SIZE+INTEL_VVP_WARP_DEBUG_INPUTS_SIZE+INTEL_VVP_WARP_DEBUG_OUTPUTS_SIZE+INTEL_VVP_WARP_ENGINES_SIZE)

/* Bit fields and masks */
#define INTEL_VVP_WARP_CONFIG_VER_MINOR_MSK					(0x0000000f)
#define INTEL_VVP_WARP_CONFIG_VER_MINOR_OFST				(0)
#define INTEL_VVP_WARP_CONFIG_VER_MAJOR_MSK					(0x000000f0)
#define INTEL_VVP_WARP_CONFIG_VER_MAJOR_OFST				(4)
#define INTEL_VVP_WARP_CONFIG_DEPTH_MSK						(0x00000f00)
#define INTEL_VVP_WARP_CONFIG_DEPTH_OFST					(8)
#define INTEL_VVP_WARP_CONFIG_STREAMS_MSK					(0x00003000)
#define INTEL_VVP_WARP_CONFIG_STREAMS_OFST					(12)
#define INTEL_VVP_WARP_CONFIG_WARP_RT						(0x00004000)
#define INTEL_VVP_WARP_CONFIG_RASTER_SCAN					(0x00008000)
#define INTEL_VVP_WARP_CONFIG_NUM_INPUT_MSK					(0x000f0000)
#define INTEL_VVP_WARP_CONFIG_NUM_INPUT_OFST				(16)
#define INTEL_VVP_WARP_CONFIG_NUM_OUTPUT_MSK				(0x00f00000)
#define INTEL_VVP_WARP_CONFIG_NUM_OUTPUT_OFST				(20)
#define INTEL_VVP_WARP_CONFIG_NUM_ENGINE_MSK				(0x07000000)
#define INTEL_VVP_WARP_CONFIG_NUM_ENGINE_OFST				(24)
#define INTEL_VVP_WARP_CONFIG_LOCAL_CHROMA_ABERR			(0x08000000)
#define INTEL_VVP_WARP_CONFIG_OBOUNCE_MSK					(0x30000000)
#define INTEL_VVP_WARP_CONFIG_OBOUNCE_OFST					(28)
#define INTEL_VVP_WARP_CONFIG_OBOUNCE_NONE					(0x00000000)
#define INTEL_VVP_WARP_CONFIG_OBOUNCE_BLOCK					(0x10000000)
#define INTEL_VVP_WARP_CONFIG_OBOUNCE_RASTER				(0x20000000)
#define INTEL_VVP_WARP_CONFIG_OBOUNCE_CHANNEL				(0x30000000)
#define INTEL_VVP_WARP_CONFIG_OUTPUT_SKIP					(0x40000000)
#define INTEL_VVP_WARP_CONFIG_CHROMA_ABERR_SUPPORT			(0x80000000)

#define INTEL_VVP_WARP_CONFIG_EXT_BANK_LOC_MSK				(0x0000001f)
#define INTEL_VVP_WARP_CONFIG_EXT_BANK_LOC_OFST				(0)
#define INTEL_VVP_WARP_CONFIG_EXT_MEMIF_WIDTH_MSK			(0x00000f00)
#define INTEL_VVP_WARP_CONFIG_EXT_MEMIF_WIDTH_OFST			(8)
#define INTEL_VVP_WARP_CONFIG_EXT_MEM_MAP_MSK				(0x00003000)
#define INTEL_VVP_WARP_CONFIG_EXT_MEM_MAP_OFST				(12)
#define INTEL_VVP_WARP_CONFIG_EXT_MEM_MAP_SDTV				(0x00000000)
#define INTEL_VVP_WARP_CONFIG_EXT_MEM_MAP_HDTV				(0x00001000)
#define INTEL_VVP_WARP_CONFIG_EXT_MEM_MAP_UHDTV				(0x00002000)
#define INTEL_VVP_WARP_CONFIG_EXT_MIPMAP_ENABLE				(0x00010000)

#define INTEL_VVP_WARP_INPUT_CONTROL_EN						(0x00000001)
#define INTEL_VVP_WARP_INPUT_CONTROL_STORE_RASTER			(0x00000002)
#define INTEL_VVP_WARP_INPUT_CONTROL_LOCK_BUFFER    		(0x00000010)
#define INTEL_VVP_WARP_INPUT_CONTROL_FRAME_CTL_MSK    		(0x000000e0)
#define INTEL_VVP_WARP_INPUT_CONTROL_FRAME_CTL_OFST    		(5)
#define INTEL_VVP_WARP_INPUT_CONTROL_CS_MSK					(0x00000300)
#define INTEL_VVP_WARP_INPUT_CONTROL_CS_OFST				(8)
#define INTEL_VVP_WARP_INPUT_CONTROL_MM_LEVEL_MSK			(0x00007000)
#define INTEL_VVP_WARP_INPUT_CONTROL_MM_LEVEL_OFST			(12)
#define INTEL_VVP_WARP_INPUT_CONTROL_SKIPP_MSK				(0x00100000)
#define INTEL_VVP_WARP_INPUT_CONTROL_SKIPP_OFST	    		(20)
#define INTEL_VVP_WARP_INPUT_CONTROL_MEM_MSK				(0xff000000)
#define INTEL_VVP_WARP_INPUT_CONTROL_MEM_OFST				(24)

#define INTEL_VVP_WARP_INPUT_RESOLUTION_H_MSK				(0x00001fff)
#define INTEL_VVP_WARP_INPUT_RESOLUTION_H_OFST				(0)
#define INTEL_VVP_WARP_INPUT_RESOLUTION_V_MSK				(0x1fff0000)
#define INTEL_VVP_WARP_INPUT_RESOLUTION_V_OFST				(16)

#define INTEL_VVP_WARP_INPUT_RAM_WR_ADDR_MSK				(0x0ffc0000)
#define INTEL_VVP_WARP_INPUT_RAM_WR_ADDR_OFST				(18)
#define INTEL_VVP_WARP_INPUT_RAM_WR_PAGE_MSK				(0x10000000)
#define INTEL_VVP_WARP_INPUT_RAM_WR_PAGE_OFST				(28)
#define INTEL_VVP_WARP_INPUT_RAM_SELECT_MSK				    (0xe0000000)
#define INTEL_VVP_WARP_INPUT_RAM_SELECT_OFST				(29)
#define INTEL_VVP_WARP_INPUT_RAM_SELECT_ORIG_RAM			(0x00000000)
#define INTEL_VVP_WARP_INPUT_RAM_SELECT_MM_RAM			    (0x20000000)

#define INTEL_VVP_WARP_OUTPUT_CONFIG_EASY_WARP_CAPABLE		(0x00100000)
#define INTEL_VVP_WARP_OUTPUT_CONFIG_BOUNCE_MSK				(0x00c00000)
#define INTEL_VVP_WARP_OUTPUT_CONFIG_BOUNCE_NBLOCK			(0x00000000)
#define INTEL_VVP_WARP_OUTPUT_CONFIG_BOUNCE_BLOCK			(0x00400000)
#define INTEL_VVP_WARP_OUTPUT_CONFIG_BOUNCE_RASTER			(0x00800000)
#define INTEL_VVP_WARP_OUTPUT_CONFIG_BOUNCE_NRASTER			(0x00c00000)

#define INTEL_VVP_WARP_OUTPUT_CONTROL_EN					(0x00000001)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_BIND_MSK				(0x0000000e)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_BIND_OFST				(1)

#define INTEL_VVP_WARP_OUTPUT_CONTROL_EASY_WARP_MSK			(0x00000070)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EASY_WARP_OFST		(4)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EASY_WARP_NONE		(0x00000000)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EASY_WARP_90CCW		(0x00000010)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EASY_WARP_180CCW		(0x00000020)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EASY_WARP_270CCW		(0x00000030)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EASY_WARP_MIRROR		(0x00000040)

#define INTEL_VVP_WARP_OUTPUT_CONTROL_CS_MSK				(0x00000300)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_CS_OFST				(8)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_STATUS_CLEAR			(0x00000400)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_LFR					(0x00000800)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_SKIPP_MSK				(0x00001000)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_SKIPP_OFST			(12)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_3DFSEQ				(0x00008000)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_3DDP					(0x00010000)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_RBIND					(0x000e0000)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_FRCTL					(0x00700000)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_MEM_MSK				(0xff000000)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_MEM_OFST				(24)

#define INTEL_VVP_WARP_OUTPUT_STATUS_LFR_STICKY_MSK         (0x00000002)
#define INTEL_VVP_WARP_OUTPUT_STATUS_LFR_STICKY_OFST        (0x00000001)

#define INTEL_VVP_WARP_OUTPUT_RESOLUTION_H_MSK				(0x00001fff)
#define INTEL_VVP_WARP_OUTPUT_RESOLUTION_H_OFST				(0)
#define INTEL_VVP_WARP_OUTPUT_RESOLUTION_V_MSK				(0x1fff0000)
#define INTEL_VVP_WARP_OUTPUT_RESOLUTION_V_OFST				(16)

#define INTEL_VVP_WARP_OUTPUT_CONTROL_EXT_H_BLOCK_MSK		(0x000000ff)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EXT_H_BLOCK_OFST		(0)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EXT_V_BLOCK_MSK		(0x0000ff00)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EXT_V_BLOCK_OFST		(8)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EXT_DBG_BLOCK_EN		(0x00010000)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EXT_DBG_BLOCK_FLASH	(0x00020000)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EXT_FREERUN			(0x01000000)
#define INTEL_VVP_WARP_OUTPUT_CONTROL_EXT_SKIPRAM_LATENCY	(0x02000000)

#define INTEL_VVP_WARP_OUTPUT_LATENCY_OFFSET_MSK			(0x00ffffff)
#define INTEL_VVP_WARP_OUTPUT_LATENCY_OFFSET_OFST			(0)

#define INTEL_VVP_WARP_ENGINE_CONFIG_CACHE_DEPTH_MSK		(0x000000ff)
#define INTEL_VVP_WARP_ENGINE_CONFIG_CACHE_DEPTH_OFST		(0)
#define INTEL_VVP_WARP_ENGINE_CONFIG_MESH_FILTERING_MSK		(0x0000c000)
#define INTEL_VVP_WARP_ENGINE_CONFIG_MESH_FILTERING_OFST	(14)
#define INTEL_VVP_WARP_ENGINE_CONFIG_PIXEL_FILTERING_MSK	(0x00030000)
#define INTEL_VVP_WARP_ENGINE_CONFIG_PIXEL_FILTERING_OFST	(16)
#define INTEL_VVP_WARP_ENGINE_CONFIG_OUTPUT_BOUNCE_MSK		(0x000C0000)
#define INTEL_VVP_WARP_ENGINE_CONFIG_OUTPUT_BOUNCE_OFST		(18)
#define INTEL_VVP_WARP_ENGINE_CONFIG_CHROMA_ABERR_MSK		(0x00300000)
#define INTEL_VVP_WARP_ENGINE_CONFIG_CHROMA_ABERR_OFST		(20)

#define INTEL_VVP_WARP_ENGINE_CONTROL_EN					(0x00000001)
#define INTEL_VVP_WARP_ENGINE_CONTROL_BIND_MSK				(0x0000000e)
#define INTEL_VVP_WARP_ENGINE_CONTROL_BIND_OFST				(1)
#define INTEL_VVP_WARP_ENGINE_CONTROL_SCAN_MSK				(0x00000030)
#define INTEL_VVP_WARP_ENGINE_CONTROL_SCAN_OFST				(4)
#define INTEL_VVP_WARP_ENGINE_CONTROL_SKIPP_MSK				(0x00000040)
#define INTEL_VVP_WARP_ENGINE_CONTROL_SKIPP_OFST			(6)
#define INTEL_VVP_WARP_ENGINE_CONTROL_FRAME_FAIL_CLEAR		(0x00000800)
#define INTEL_VVP_WARP_ENGINE_CONTROL_LOWLAT_PROTECT		(0x00001000)
#define INTEL_VVP_WARP_ENGINE_CONTROL_CS_MSK				(0x03000000)
#define INTEL_VVP_WARP_ENGINE_CONTROL_CS_OFST				(24)

#define INTEL_VVP_WARP_ENGINE_STATUS_FRAME_FAIL_MSK			(0x00000010)
#define INTEL_VVP_WARP_ENGINE_STATUS_FRAME_FAIL_OFST		(4)

#define INTEL_VVP_WARP_ENGINE_COEF_CTRL_FETCH_MSK			(0x000000ff)
#define INTEL_VVP_WARP_ENGINE_COEF_CTRL_FETCH_OFST			(0)
#define INTEL_VVP_WARP_ENGINE_COEF_CTRL_MESH_MSK			(0x0000ff00)
#define INTEL_VVP_WARP_ENGINE_COEF_CTRL_MESH_OFST			(8)
#define INTEL_VVP_WARP_ENGINE_COEF_CTRL_FILTER_MSK			(0x00ff0000)
#define INTEL_VVP_WARP_ENGINE_COEF_CTRL_FILTER_OFST			(16)

#define INTEL_VVP_WARP_ENGINE_GEOMETRY_START_H_MSK			(0x000001ff)
#define INTEL_VVP_WARP_ENGINE_GEOMETRY_START_H_OFST			(0)
#define INTEL_VVP_WARP_ENGINE_GEOMETRY_START_V_MSK			(0x03ff0000)
#define INTEL_VVP_WARP_ENGINE_GEOMETRY_START_V_OFST			(16)
#define INTEL_VVP_WARP_ENGINE_GEOMETRY_END_H_MSK			(0x000001ff)
#define INTEL_VVP_WARP_ENGINE_GEOMETRY_END_H_OFST			(0)
#define INTEL_VVP_WARP_ENGINE_GEOMETRY_END_V_MSK			(0x03ff0000)
#define INTEL_VVP_WARP_ENGINE_GEOMETRY_END_V_OFST			(16)

#define INTEL_VVP_WARP_ENGINE_RAM_WR_ADDR_MSK				(0x0ffc0000)
#define INTEL_VVP_WARP_ENGINE_RAM_WR_ADDR_OFST				(18)
#define INTEL_VVP_WARP_ENGINE_RAM_WR_PAGE_MSK				(0x10000000)
#define INTEL_VVP_WARP_ENGINE_RAM_WR_PAGE_OFST				(28)
#define INTEL_VVP_WARP_ENGINE_RAM_SELECT_MSK				(0xe0000000)
#define INTEL_VVP_WARP_ENGINE_RAM_SELECT_OFST				(29)
#define INTEL_VVP_WARP_ENGINE_RAM_SELECT_SKIP_RAM			(0x80000000)

#define INTEL_VVP_WARP_ENGINE_MESH_CTL_STRIDE_MSK			(0x00000fff)
#define INTEL_VVP_WARP_ENGINE_MESH_CTL_STRIDE_OFST			(0)
#define INTEL_VVP_WARP_ENGINE_MESH_CTL_RES_MSK			    (0x03000000)
#define INTEL_VVP_WARP_ENGINE_MESH_CTL_RES_OFST 			(24)
#define INTEL_VVP_WARP_ENGINE_MESH_CTL_PREC_MSK			    (0x0c000000)
#define INTEL_VVP_WARP_ENGINE_MESH_CTL_PREC_OFST			(26)

#define INTEL_VVP_WARP_COEFF_CTRL_SIZE_128KB					(0x01)
#define INTEL_VVP_WARP_COEFF_CTRL_SIZE_256KB					(0x02)
#define INTEL_VVP_WARP_COEFF_CTRL_SIZE_512KB					(0x04)
#define INTEL_VVP_WARP_COEFF_CTRL_SIZE_1024KB					(0x08)
#define INTEL_VVP_WARP_COEFF_CTRL_SIZE_2048KB					(0x10)
#define INTEL_VVP_WARP_COEFF_CTRL_SIZE_4096KB					(0x20)
#define INTEL_VVP_WARP_COEFF_CTRL_SIZE_8192KB					(0x40)

#define INTEL_VVP_WARP_DATA_SIZE_128KB						(0x020000)
#define INTEL_VVP_WARP_DATA_SIZE_256KB						(0x040000)
#define INTEL_VVP_WARP_DATA_SIZE_512KB						(0x080000)
#define INTEL_VVP_WARP_DATA_SIZE_1024KB						(0x100000)
#define INTEL_VVP_WARP_DATA_SIZE_2048KB						(0x200000)
#define INTEL_VVP_WARP_DATA_SIZE_4096KB						(0x400000)
#define INTEL_VVP_WARP_DATA_SIZE_8192KB						(0x800000)

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /*__INTEL_VVP_WARP_REGS_H__*/
