/*******************************************************************************
Copyright (C) Altera Corporation

This code and the related documents are Altera copyrighted materials and your
use of them is governed by the express license under which they were provided to
you ("License"). This code and the related documents are provided as is, with no
express or implied warranties other than those that are expressly stated in the 
License.
*******************************************************************************/

#ifndef _INTEL_VVP_TMO_REGS_H_
#define _INTEL_VVP_TMO_REGS_H_

#ifdef __cplusplus
extern "C" {
#endif /*__cplusplus*/

/*
	Offset added by the front-end slave interface = 64 + 18
	This offset already takes into account the new commit register as per VVP Spec
*/
#define INTEL_VVP_TMO_FRONT_END_IF_OFFSET (0x0148 >> 2)

#define INTEL_VVP_TMO_HW_INFO_0			(0 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_HW_INFO_1			(1 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_HW_INFO_2			(2 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_FLOW_CTL			(3 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_ACT_GEOM			(4 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_VOL_CTL			(5 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_CENTRE_TILE_WIDTH	(6 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_CORNER_TILE_NORM	(7 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_X_TILE_NORM		(8 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_Y_TILE_NORM		(9 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_CENTRE_TILE_NORM	(10 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_ACT_TILE_DIM		(11 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_00	(12 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_01	(13 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_02	(14 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_03	(15 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_04	(16 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_05	(17 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_06	(18 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_07	(19 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_08	(20 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_09	(21 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_10	(22 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_11	(23 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_12	(24 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_13	(25 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_14	(26 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_15	(27 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_16	(28 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_17	(29 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_18	(30 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_19	(31 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_20	(32 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_21	(33 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_BORDER_INFO_22	(34 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_ROI_X0X1          (35 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_ROI_Y0Y1          (36 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)
#define INTEL_VVP_TMO_DBG_INFO			(40 + INTEL_VVP_TMO_FRONT_END_IF_OFFSET)

/*
	Bit field masks and offsets
*/

#define INTEL_VVP_TMO_HW_INFO_0_DEPTH_MSK		0x0000000f
#define INTEL_VVP_TMO_HW_INFO_0_DEPTH_OFST		0
#define INTEL_VVP_TMO_HW_INFO_0_PIXELS_MSK		0x00000f00
#define INTEL_VVP_TMO_HW_INFO_0_PIXELS_OFST		8
#define INTEL_VVP_TMO_HW_INFO_0_TILE_MSK		0x0f000000
#define INTEL_VVP_TMO_HW_INFO_0_TILE_OFST		24

#define INTEL_VVP_TMO_HW_INFO_2_NORM_FACT_MSK	0x000007ff
#define INTEL_VVP_TMO_HW_INFO_2_NORM_FACT_OFST	0

#define INTEL_VVP_TMO_FLOW_CTL_PASSTHROUGH_MASK	0x00000001
#define INTEL_VVP_TMO_FLOW_CTL_PASSTHROUGH_OFST	0
#define INTEL_VVP_TMO_FLOW_CTL_SOFT_RST_MASK	0x80000000
#define INTEL_VVP_TMO_FLOW_CTL_SOFT_RST_OFST	31

#define INTEL_VVP_TMO_ACT_GEOM_HEIGHT_MASK		0x00003fff
#define INTEL_VVP_TMO_ACT_GEOM_HEIGHT_OFST		0
#define INTEL_VVP_TMO_ACT_GEOM_WIDTH_MASK		0x3fff0000
#define INTEL_VVP_TMO_ACT_GEOM_WIDTH_OFST		16

#define INTEL_VVP_TMO_VOL_CTL_VOLUME_MASK		0x007f0000
#define INTEL_VVP_TMO_VOL_CTL_VOLUME_OFST		16
#define INTEL_VVP_TMO_VOL_CTL_THRESHOLD_MASK	0x00003fff
#define INTEL_VVP_TMO_VOL_CTL_THRESHOLD_OFST	0

#define INTEL_VVP_TMO_CENTRE_TILE_WIDTH_MASK	0xffff0000
#define INTEL_VVP_TMO_CENTRE_TILE_WIDTH_OFST	16

#define INTEL_VVP_TMO_ACT_TILE_DIM_HEIGHT_MASK	0x0000ffff
#define INTEL_VVP_TMO_ACT_TILE_DIM_HEIGHT_OFST	0
#define INTEL_VVP_TMO_ACT_TILE_DIM_WIDTH_MASK	0xffff0000
#define INTEL_VVP_TMO_ACT_TILE_DIM_WIDTH_OFST	16

#define INTEL_VVP_TMO_BORDER_INFO_GROUP_0_MASK	0x3fff0000
#define INTEL_VVP_TMO_BORDER_INFO_GROUP_0_OFST	16
#define INTEL_VVP_TMO_BORDER_INFO_GROUP_1_MASK	0x00003fff
#define INTEL_VVP_TMO_BORDER_INFO_GROUP_1_OFST	0

#ifdef __cplusplus
}
#endif /*__cplusplus*/

#endif /* _INTEL_VVP_TMO_REGS_H_ */
