BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*.bb"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-vvp-isp-demo"
BBFILE_PATTERN_meta-vvp-isp-demo = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-vvp-isp-demo = "7"

LAYERDEPENDS_meta-vvp-isp-demo = "core"
LAYERSERIES_COMPAT_meta-vvp-isp-demo = "nanbield scarthgap"

WKS_FILE="vvp-isp-demo-image.wks"

# IMAGE_BOOT_FILES defaults set in meta-altera-bsp/conf/machine/include/socfpga-boot.inc
