# *******************************************************************************
# Copyright (C) Altera Corporation
#
# This code and the related documents are Altera copyrighted materials and your
# use of them is governed by the express license under which they were provided to
# you ("License"). This code and the related documents are provided as is, with no
# express or implied warranties other than those that are expressly stated in the 
# License.
# *******************************************************************************/

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-altera-fpga-ocs"
BBFILE_PATTERN_meta-altera-fpga-ocs = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-altera-fpga-ocs = "6"

LAYERSERIES_COMPAT_meta-altera-fpga-ocs = "nanbield scarthgap"

ERROR_QA:remove = "buildpaths"
WARN_QA:append = " buildpaths"
